---
galaxy_info:
  role_name: batch
  author: Michael Bredemeier
  description: Apply many work item definitions in one call
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - azure
    - azuredevops
dependencies: []
